### ISSUE TITLE
 Error: Ensure GITHUB_TOKEN has permission "id-token: write"

### ISSUE THREAD

**Issue by skywarth** [Mr-fangao/Mr-fangao.github.io#1]
Hey there,

I saw that your build fails due to ` Error: Ensure GITHUB_TOKEN has permission "id-token: write"` error. You can resolve this error simply by adding the following permissions to your `ci.yml` file:

```
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
```

You have to add it between `on:` and `jobs:`. Like so:

```
name: CI
 
on:
#your other codes...

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
#your other codes...
```

I believe it will solve the [build error](https://github.com/Mr-fangao/Mr-fangao.github.io/actions/runs/5276169550/jobs/9542527516) you've received in your recent action run.
